### ISSUE TITLE
Can you provide the trained model file so that I can download?

### ISSUE THREAD

**Issue by machanic** [mswzeus/WideResNet-Adversarial-Training-PyTorch#1]
Can you provide the trained model file so that I can download? Where is model file to download?

**Comment by seonwoo-min** [comment]
Hi, @machanic,
Thanks for your interest in my repository.

Originally, I did not upload the pre-trained models due to their large model sizes.
Now you can find the pre-trained models in the _results_ directory. 
Note that you need to use Git LFS to pull the updated files. (https://www.atlassian.com/git/tutorials/git-lfs)

**Comment by machanic** [comment]
Thank you very much!
